// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/vanilla": {
    params: {};
  };
  "/react": {
    params: {};
  };
  "/angular": {
    params: {};
  };
  "/meeting": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/vanilla" | "/react" | "/angular" | "/meeting";
  };
  "./layout.tsx": {
    id: "layout";
    page: "/" | "/vanilla" | "/react" | "/angular" | "/meeting";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./pages/vanilla/index.tsx": {
    id: "pages/vanilla/index";
    page: "/vanilla";
  };
  "./pages/react/index.tsx": {
    id: "pages/react/index";
    page: "/react";
  };
  "./pages/angular/index.tsx": {
    id: "pages/angular/index";
    page: "/angular";
  };
  "./pages/meeting/index.tsx": {
    id: "pages/meeting/index";
    page: "/meeting";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout": typeof import("./app/./layout.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "pages/vanilla/index": typeof import("./app/./pages/vanilla/index.tsx");
  "pages/react/index": typeof import("./app/./pages/react/index.tsx");
  "pages/angular/index": typeof import("./app/./pages/angular/index.tsx");
  "pages/meeting/index": typeof import("./app/./pages/meeting/index.tsx");
};