export const pillsConfig = [
  "RealtimeKitClient.init",
  "meeting.self.permissions",
  "meeting.participants.joined",
  "meeting.meta.roomName",
  "meeting.plugins.enable",
  "meeting.chat.messages",
  "meetings.polls.get",
  "meeting.stage.leave",
  "meeting.stage.join",
  "meeting.joinRoom",
  "meeitng.initMedia",
  "meeting.meta.roomName",
  "meeting.plugins.enable",
  "meeting.chat.messages",
  "meetings.polls.get",
];
