const sampleFiles = [
  {
    name: "active-speaker-ui",
    platform: "web",
    id: "react-examples/active-speaker-ui",
    url: "https://react-examples.realtime.cloudflare.com/active-speaker-ui",
    preset: "Webinar Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/active-speaker-ui",
    description: "A video meeting UI that automatically highlights the current active speaker.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Async%20Interview%20Platform.png",
    usecase: "webinar",
  },
  {
    name: "async-video-survey",
    platform: "web",
    id: "react-examples/async-video-survey",
    url: "https://react-examples.realtime.cloudflare.com/async-video-survey",
    preset: "Video Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/async-video-survey",
    description: "An asynchronous video survey flow where respondents record answers without a live call.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Async%20Survey.png",
    usecase: "video",
  },
  {
    name: "audio-room",
    platform: "web",
    id: "react-examples/audio-room",
    url: "https://react-examples.realtime.cloudflare.com/audio-room",
    preset: "Audio Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/audio-room",
    description: "A live audio-only room experience for discussions, panels, and community hangouts.",
    blogUrl:"",
   picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Calling%20App%20-%20Flutter.png",
    usecase: "audio",
  },
  {
    name: "back-to-back-meetings",
    platform: "web",
    id: "react-examples/back-to-back-meetings",
    url: "https://react-examples.realtime.cloudflare.com/back-to-back-meetings",
    preset: "Video Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/back-to-back-meetings",
    description: "A multi-session meeting experience optimized for running consecutive meetings.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Calling%20App%20-%20WPF.png",
    usecase: "video",
  },
  {
    name: "clubhouse",
    platform: "web",
    id: "react-examples/clubhouse",
    url: "https://react-examples.realtime.cloudflare.com/clubhouse",
    preset: "Livestream Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/clubhouse",
    description: "A stage-and-audience style live audio experience with moderated participation.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Chat%20App%20-%20Angular.png",
    usecase: "livestream",
  },
  {
    name: "create-your-own-ui",
    platform: "web",
    id: "react-examples/create-your-own-ui",
    url: "https://react-examples.realtime.cloudflare.com/create-your-own-ui",
    preset: "Video Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/create-your-own-ui",
    description: "A minimal starter showing how to build a fully custom RealtimeKit UI.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Transcription%20in%20Video%20Calling%20App.png",
    usecase: "video",
  },
  {
    name: "default-meeting",
    platform: "web",
    id: "react-examples/default-meeting-ui",
    url: "https://react-examples.realtime.cloudflare.com/default-meeting-ui",
    preset: "",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/default-meeting",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Calling%20App%20-%20React.png",
    description: "The standard batteries-included meeting UI showcasing the default RealtimeKit experience.",
    blogUrl:"",
    usecase: "all",
  },
  {
    name: "facetime",
    platform: "web",
    id: "react-examples/facetime",
    url: "https://react-examples.realtime.cloudflare.com/facetime",
    preset: "Video Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/facetime",
    description: "A FaceTime-inspired calling UI with a familiar layout and interactions.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Live%20Proctoring%20System%20-%20II.png",
    usecase: "video",
  },
  {
    name: "live-auction",
    platform: "web",
    id: "react-examples/live-auction",
    url: "https://react-examples.realtime.cloudflare.com/live-auction",
    preset: "Livestream Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/live-auction",
    description: "A livestream-oriented experience tailored for real-time auctions.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Live%20Auction.png",
    usecase: "livestream",
  },
  {
    name: "multi-meeting",
    platform: "web",
    id: "react-examples/multi-meeting",
    url: "https://react-examples.realtime.cloudflare.com/multi-meeting",
    preset: "Video Call Host Demo",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/multi-meeting",
    description: "A multi-room meeting demo for managing and switching between multiple sessions.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Calling%20App%20-%20Electron.png",
    usecase: "video",
  },
  {
    name: "background-effects",
    platform: "web",
    id: "react-examples/with-background-effects",
    url: "https://react-examples.realtime.cloudflare.com/with-background-effects",
    preset: "",
    githubUrl: "https://github.com/cloudflare/realtimekit-web-examples/tree/main/react-examples/examples/with-background-transformer",
    description: "A video calling demo with background blur/replacement using a video transformer pipeline.",
    blogUrl:"",
    picture: "https://rtk-assets.realtime.cloudflare.com/examples/Video%20Calling%20App%20with%20AR%20Filters.png",
    usecase: "all",
  }
];

export default sampleFiles;